CREATE DATABASE questiongo;
CREATE TABLE questiongo.data (id BIGINT UNSIGNED AUTO_INCREMENT, questionnaire VARCHAR(600) NOT NULL, question VARCHAR(600) NOT NULL, data LONGTEXT NOT NULL, PRIMARY KEY(id));
